#!/usr/bin/env python3
"""Derive a reproducible one-beam azimuth-localization Stage2 case.

The script changes only scenario controls; radar waveform, target geometry and
the algorithm XML remain generated by Stage2.  It is deliberately useful for
paired 4-channel and 2-channel A/B runs without copying experiment JSON files.
"""

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--template", default="configs/stage2/azimuth_localization_paired_smoke.json")
    parser.add_argument("--output", required=True)
    parser.add_argument("--case-id", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--channels", type=int, choices=(2, 4), default=4)
    parser.add_argument("--phase-center-mode", choices=("physical", "paired_same_phase_center"), default="paired_same_phase_center")
    parser.add_argument("--seed", type=int, default=20260812)
    parser.add_argument("--snr-db", type=float, default=45.0)
    parser.add_argument("--noise-power", type=float, default=0.0)
    parser.add_argument("--clutter-scale", type=float, default=0.0)
    parser.add_argument("--scan-angle-deg", type=float, default=0.0)
    parser.add_argument("--azimuth-offset-deg", type=float, default=0.0)
    parser.add_argument("--expected-bin", type=int, default=2200)
    args = parser.parse_args()

    if args.channels == 2 and args.phase_center_mode != "physical":
        parser.error("paired_same_phase_center is a four-channel-only control")
    if args.noise_power < 0.0:
        parser.error("--noise-power must be non-negative")

    with open(args.template, encoding="utf-8") as f:
        cfg = json.load(f)
    cfg["case_id"] = args.case_id
    cfg["output_dir"] = args.output_dir
    cfg["waveform"]["new_protocol_channel_count"] = args.channels
    # Keep one physical, explicitly commanded beam per case.  This prevents
    # neighbouring-beam visibility from contaminating localization statistics.
    cfg["scan"]["scan_min_deg"] = args.scan_angle_deg
    cfg["scan"]["beam_count"] = 1
    cfg["random"]["random_seed"] = args.seed
    cfg["random"]["four_channel_phase_center_mode"] = args.phase_center_mode
    cfg["scene"]["clutter_amplitude_scale"] = args.clutter_scale
    cfg["scene"]["thermal_noise"] = {
        "enabled": args.noise_power > 0.0,
        "noise_power": args.noise_power,
        "include_target_only": True,
    }
    cfg["targets"][0]["amplitude"] = {"type": "snr_db", "snr_db": args.snr_db}
    cfg["targets"][0]["init"]["beam_id"] = 1
    cfg["targets"][0]["init"]["expected_bin"] = args.expected_bin
    cfg["targets"][0]["init"]["azimuth_offset_deg"] = args.azimuth_offset_deg
    if args.channels == 2:
        cfg["channel_geometry"] = {
            "channel_1": cfg["channel_geometry"]["channel_1"],
            "channel_2": cfg["channel_geometry"]["channel_2"],
        }

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
